### ISSUE TITLE
Feature request -- inline mutable version of bit vector

### ISSUE THREAD

**Issue by rvnath** [infusion/BitSet.js#10]
I understand that the current version of bitset returns a new copy of bitset for every bit op.  Isn't it costly, especially for large bitsets to get a new object?  Can we have an inline version please...?

**Comment by infusion** [comment]
I changed this behavior with 3.0.0 and surprisingly, there is not the big difference as one would expect, since instantiation of a prototyped class is quite fast. I'm currently working on the class, making it even faster. When I finish my current work, I'll back port it to a "inline version" as a reference of performance benchmarks.

**Comment by infusion** [comment]
BitSet now is mutable.
