### ISSUE TITLE
If the data is completely zero, then count leading zeros and count trailing zeros should return the word size

### ISSUE THREAD

**Issue by CMCDragonkai** [infusion/BitSet.js#21]
I'm working on fixed size bitsets, and I create a 64 bit bitset by doing: `new BitSet(new Uint8Arrray(4))`.

When calling `ntz()` on this object, it returns `Infinity`, IMO it should return the size of the bitmap which in this case is 64.

> If the word is zero (no bits set), count leading zeros and count trailing zeros both return the number of bits in the word, while ffs returns zero. Both log base 2 and zero-based implementations of find first set generally return an undefined result for the zero word.
> https://en.wikipedia.org/wiki/Find_first_set#Algorithms

While ffs is something that could return `Infinity`.

**Comment by infusion** [comment]
Thanks for the ticket, that makes sense. What I don't get is how you get a 64 bit bitset with 4*8bit. Even if the 8bit array is mapped 1:1  to the internal 31 bit Array structure, it's 4*31=124bit.

**Comment by CMCDragonkai** [comment]
My understanding is that Uint8Array(4) creates 4 of 8 bit ints. This
triggers an extension from 32 bit to 64 bits based on your fixed wordsize
of 32 bits. I tested it and it behaved that way.

**Comment by infusion** [comment]
Okay, I see your point now. Even if Bitset.js allocates 64 bits, it doesn't mean it's the actual size. Consider the following:

```
console.log(new BitSet(new Uint8Array([1,2,3,4])))
```
which produces: `{ data: [ 67305985, 0 ] }`

That means the whole 4 bytes are packed into the 32bit integer - which makes sense. The additional zero is just a slight extension for performance reasons, since it could happen that one of the proceeding bits is touched soon.

So, I see your point here. Also on the whole topic, that 64 should be returned. But it isn't correct and doesn't make too much sense, since the internal _allocated_ data doesn't represent the external state. And things are getting even more complicated with #22. Since Bitset.js provides arbitrarily large bit vectors, Infinity is the only reasonable answer to `ntz()`. You bring additional knowledge into play here, since you know JavaScript works on 32bit integers and as such Bitset.js does. But the purpose of this library is to abstract over this limitation.

Could you elaborate on how you want to use ntz with a bit vector of all zeros? What would 64 mean to you in your application?

**Comment by CMCDragonkai** [comment]
It doesn't matter atm, I wrote an adapter around the bitset functions making it more closer to the API I expected. But checking for Infinity is not any different as checking for ntz = bitmap size in my case.

**Comment by infusion** [comment]
The thing is, that I don't have the actual bitmap size. I could return `arr.length*32`, but as I said this doesn't reflect the actual bitmap size, since bitset.js pre-allocates the array with zeros to reduce execution time on stressful environments. I decided to do so, when I fought with Daniel Lemire's fastbitset to win the battle. In a later step I decided to make Bitset.js working with negations - that's where the '_'-attribute was born. This change made Bitset.js an arbitrarily large bit vector implementation, for which ntz=Infty is the most logical answer.

That's why I'd like to keep it the way it is. If you're still against the implementation, could provide a reasoning under the set restrictions, mentioned earlier?

**Comment by CMCDragonkai** [comment]
I'm using it for this: https://github.com/MatrixAI/js-resource-counter btw. BitSet is fine currently.

**Comment by infusion** [comment]
This is a pretty cool use case for Bitset.js! Matrix.ai is a nice project, are u working alone on it?

**Comment by CMCDragonkai** [comment]
Thanks. Got 1 other team member and 2 other consultants.

**Comment by infusion** [comment]
So, can we close this ticket as well? I mean, Infinity is the only reasonable result and it doesn't make any difference in your code. I added a small note on the `ntz` doc entry about this behavior.
