### ISSUE TITLE
[Question] Optimized for large ranges of the same value?

### ISSUE THREAD

**Issue by woodser** [infusion/BitSet.js#30]
Does this library optimize large ranges of the same value?

For example, if 1 million bits are marked true, then 1 million false, then one million true, is this internally represented using ranges to compress the information and optimize lookups?

Can such a format be exported/imported to/from JSON?

Perhaps there is another better suited data structure for this purpose?

Thank you.

**Comment by infusion** [comment]
Hi woodser, nope the bitsets are expected to be uniformly sampled and dense, which does not allow for optimizations like this. I think the best idea to solve this problem is having a run-length encoded string, which lets you solve a lookup in O(k) where k is the number of set bits. If k is very small, you have a super fast algorithm to check even for bitsets of large size.

**Comment by infusion** [comment]
run-length encoded strings as input for BitSet.js would be a nice feature.

**Comment by woodser** [comment]
Ok, thank you for the quick response.

I wrote a utility to represent unbound boolean arrays which optimizes for large ranges of the same value by internally representing the data as a series of ranges.  It's experimental and can be optimized further but here it is if it interests you: [BooleanSet.js](https://github.com/woodser/monero-javascript/blob/BooleanSet/src/utils/BooleanSet.js).

I wanted to see if this package could provide the similar functionality more efficiently.  I think it would great addition.

Thank you.
