### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by can-keklik** [infusion/BitSet.js#32]
Hello,

First of all, bitset.js is a really useful tool. Thanks for your efforts.

My question is about memory usage of a BitSet. I assume that a BitSet is as large as of its MSB. Let's say we have a BitSet whose 300,000,000th bit is set as 1, remaining are zero. We need to allocate 300M bits, right? If so, total size should be around ~35.7 MB. However, when I execute this scenario (set 300Mth bit as 1), BitSet size is calculated as 194.5 MB. I use an npm package `object-sizeof` to do that. I naturally don't expect it to allocate exactly 300M bits, instead a close number which is better for memory management. But the difference is huge. So, which is correct? Do I misunderstand something? 

Thanks.

**Comment by infusion** [comment]
Thanks :)

Nice observation, Bitset.js stores the data as an array of integers internally. This means that 32 bits are stored in one number leading to 300.000.000/32= ~10M elements * 4byte per integer leading to around 40M as you say. The problem now is that normal JavaScript arrays are used and not typed arrays. This decision has two main reasons: Typed arrays are not available on every engine and typed arrays have a very slow startup time - and I want the library as fast as possible. For now this means that array size depends on the actual implementation of objects and especially the Array object. I will rewrite the code in C++ soon to provide the library as a webassembly implementation. 
I had a similar ticket a while ago asking for quite the same as you do, but I would go with a simple hashmap then. The current implementation is optimized for dense bitsets. 

Robert

**Comment by can-keklik** [comment]
If you recommend hashmap for sparsity, I have fairly dense vectors (but there can be large paddings). Actually I implemented a version which uses Set class and they were similar in terms of performance (haven't compared memory usage). But I will need to use more complex (multiple ANDs, ORs, etc.) logic operations, that's also why I wanted to use bitsets and of course for less memory footprint. 

But... I am focused on your statement about the arrays. You basically say that, in theory, my computation was fine. However, since you use Array instead of Typed Array, the computed size, 194.5 MB, is practically correct. If so, the difference is really enormous, almost ~5 times larger than expected. So is it impractical to use BitSets for my case? 

BTW, I need it only for Node environment, no browser and another stuff.

**Comment by infusion** [comment]
I would go with Bitsets since the library is optimized heavily for performance and is tested a lot for logical operations. Implementing them  on your own, especially with complex logical scenarios on hashmaps can lead to strange bugs. Why do you concern memory foodprint that much? Are you on a legacy or an embedded device? I just read the source of your mentioned `object-sizeof` package and it calculates just an estimate of the size, so what V8 really does and what memory is actually used can't be said by the module. You could measure that again with D8 for example.

About your size question: I follow the developments of V8 internals here and there and arrays are not arrays like in C/C++. They are containers to store any set of arrays, they have to implement stack-like features (push()/pop()) and so on. This leads to a certain memory overhead. Five times sounds quite a lot, but the engine gets improved every day. Maybe they find a way to improve the memory foodprint and it will be better in the next version. If the 200MB is a problem for you, because you are on a raspberry pi or such, I would change the algorithm and split it into 10x 1M bit bitsets.

**Comment by can-keklik** [comment]
I am concerned because this code will run per request on a web server. Request size is independent and is significantly small (and probably cached). So only thing is memory peaks. Even though 300M is quite a big number (and I don't think that I'll need it such a set in near future), I'll probably use a collection of smaller bitsets (max 50 let's say). And the most significant bit will monotonically increase in those (like 1M for each bucket). So you can imagine that total size increases 1M for each bitset. This is also an edge scenario, however, it is not impossible. Good news, server resources will be proportional to the size of data that needs to be crunched. But I still think that few hundreds of megabytes is big for a single request (Maybe I am wrong?).

You're probably right about `object-sizeof`, its measurements didn't seem precise to me too. But when node crashes because of memory error, I understand that there is a great need of memory. Not a method really, but an indicator let me say. 

Regarding changing the algorithm, I think It would be a premature optimization, at least for now. I need to do more experiments to really want something like that. Thank you for your attention.

**Comment by harrysarson** [comment]
Hi @infusion, purely for academic interest, could you link me some info about typed-arrays having a slow start-up time? I have not heard about this before. Thanks :)

**Comment by harrysarson** [comment]
Very interesting, thanks for the reply!

**Comment by infusion** [comment]
@can-keklik I think there are many options to improve performance when considering app knowledge, like is the per request object needed or is one single global object sufficient? Can parts of it be cached (like bit ranges?). When 300M bits are the worst case, make sure to optimize for the variance of the request time and not the worst case scenario. When 300M can occur and is fast enough (and can't lead to a DOS attack), it should be fine when most requests must handle only a fraction of it.
But it all depend on the request concurrency. 10 req/day is easier than 10/sec. >100MB for a single request sounds much, but as you say hardware gets cheaper and software quality pushes pretty hard towards Moores Law. With BitSet running on webasm and a better V8 in the future will give you power to keep the stack. Of course, node.js shouldn't crash because of the memory demand ;)

**Comment by can-keklik** [comment]
@infusion Thanks for the comprehensive response. Global object is not a case, information is only needed in request contexts. Caching bit ranges may work, if bit distribution is compact enough. DOS is not possible I guess. Of course, this type of huge requests will not be that frequent. Also, I can cache results to implicitly limit it. Working on, it will be fine somehow. Also, I look forward to new optimizations for BitSet.js, bit representations are so underrated I think :slightly_smiling_face:.

BTW, I have an another question. This is just out of curiosity. Does setting only 300Mth bit to 1 equal to setting all bits between zero and 300M to 1? I mean theoretically they should use the same space, right? I used Chrome DevTools to profile usage for both cases and BitSet uses ~100MB (not 194MB as I said before, ~2.5 times more than standard bit representation) in that case. So, when I set the bit at 3E26 (gigantic), it uses almost nothing (only 4K). Obviously there is a trick, but what is it?
